version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: files-nes
    environment:
      - POSTGRES_USER=grails_user
      - POSTGRES_PASSWORD=grails_password
      - POSTGRES_DB=file-nest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - grails_network

volumes:
  postgres_data:
    driver: local

networks:
  grails_network:
    driver: bridge